# Form implementation generated from reading ui file '/home/chris/careweather/SerialKiller2/ui_files/plot_key_popup.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_key_popup(object):
    def setupUi(self, key_popup):
        key_popup.setObjectName("key_popup")
        key_popup.resize(561, 267)
        self.gridLayout = QtWidgets.QGridLayout(key_popup)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = KeyTableWidget(parent=key_popup)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.buttonBox_ok = QtWidgets.QDialogButtonBox(parent=key_popup)
        self.buttonBox_ok.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox_ok.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox_ok.setObjectName("buttonBox_ok")
        self.gridLayout.addWidget(self.buttonBox_ok, 3, 1, 1, 1)
        self.toolButton_add_row = QtWidgets.QToolButton(parent=key_popup)
        self.toolButton_add_row.setObjectName("toolButton_add_row")
        self.gridLayout.addWidget(self.toolButton_add_row, 3, 0, 1, 1)
        self.label_debug = QtWidgets.QLabel(parent=key_popup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_debug.sizePolicy().hasHeightForWidth())
        self.label_debug.setSizePolicy(sizePolicy)
        self.label_debug.setWordWrap(True)
        self.label_debug.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_debug.setObjectName("label_debug")
        self.gridLayout.addWidget(self.label_debug, 0, 0, 1, 2)

        self.retranslateUi(key_popup)
        self.buttonBox_ok.accepted.connect(key_popup.accept) # type: ignore
        self.buttonBox_ok.rejected.connect(key_popup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(key_popup)

    def retranslateUi(self, key_popup):
        _translate = QtCore.QCoreApplication.translate
        key_popup.setWindowTitle(_translate("key_popup", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("key_popup", "New Row"))
        self.toolButton_add_row.setText(_translate("key_popup", "+ Add Row"))
        self.label_debug.setText(_translate("key_popup", "\'\'"))
from SK_widgets import KeyTableWidget
